credentials:
  usernames:
    wsantos:
      email: testando@gmail.com
      logged_in: False
      name: Wellinton Oliveira
      password: abcd1234
    jferreira:
      email: testando1@gmail.com
      logged_in: False
      name: Joaquim Ferreira
      password: abcd1234
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name